In [1]:
import numpy as np

In [2]:
# Creating numpy array

In [3]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list)

In [5]:
x

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)
# [[ - means two dimentional data set

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
list(range(5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# pandas will convert int to float, not to lose data

In [16]:
np.zeros((5,5)) # first rows, second columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0, 10, 3) 

array([ 0.,  5., 10.])

In [22]:
np.linspace(0, 10, 31) # linearly(evenly) spaced

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667,  2.        ,  2.33333333,  2.66666667,  3.        ,
        3.33333333,  3.66666667,  4.        ,  4.33333333,  4.66666667,
        5.        ,  5.33333333,  5.66666667,  6.        ,  6.33333333,
        6.66666667,  7.        ,  7.33333333,  7.66666667,  8.        ,
        8.33333333,  8.66666667,  9.        ,  9.33333333,  9.66666667,
       10.        ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(3,3) # uniform 0 to 1

array([[0.66239544, 0.1927528 , 0.60444036],
       [0.85882802, 0.34527034, 0.40903747],
       [0.93397268, 0.46998563, 0.08774112]])

In [30]:
np.random.randn(3,3)# normal mean 0 var 1

array([[ 0.65129888, -0.41567779, -0.23100574],
       [-1.19604103,  1.04168622,  0.17956758],
       [ 1.73958926, -0.51740144, -0.6110934 ]])

In [31]:
np.random.randint(1, 101)

61

In [32]:
np.random.seed() # it exists here

In [34]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
ranarr

array([28, 19, 36, 22,  4, 19,  6,  3, 15, 36])

In [46]:
arr.reshape(5,5, order = "C") # order by row or column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.shape

(25,)

In [48]:
arr.reshape(5,5).shape

(5, 5)

In [50]:
ranarr.max()

36

In [52]:
ranarr.argmax() #  the first match

2

In [54]:
ranarr.min()

3

In [55]:
ranarr.argmin()

7